# Generated by Django 4.0.4 on 2022-06-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLG_App', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='weightclass',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
