# Generated by Django 4.0.4 on 2022-06-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLG_App', '0003_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('M', "Boy's"), ('F', "Girl's")], max_length=1),
        ),
    ]
