# Generated by Django 4.0.4 on 2022-06-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLG_App', '0004_alter_team_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pictures'),
        ),
    ]
