# Generated by Django 4.0.4 on 2022-06-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLG_App', '0007_remove_posts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
