# Generated by Django 4.0.4 on 2022-06-22 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TLG_App', '0008_alter_athlete_team_imagegallery'),
        ('TLG_App', '0008_posts_date'),
    ]

    operations = [
    ]
