# Generated by Django 4.0.4 on 2022-06-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLG_App', '0010_alter_team_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='dob',
            field=models.DateField(),
        ),
    ]
