# Generated by Django 4.0.4 on 2022-06-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLG_App', '0011_alter_athlete_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='weightclass',
            field=models.CharField(max_length=255),
        ),
    ]
