# Generated by Django 4.0.4 on 2022-07-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLG_App', '0013_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start',
            field=models.DateField(),
        ),
    ]
