# Generated by Django 4.0.4 on 2022-07-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLG_App', '0014_alter_calendar_end_alter_calendar_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
