# Generated by Django 4.0.4 on 2022-07-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_proflile_picture_useraccount_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='profile_picture',
        ),
    ]
